# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-13 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='idk', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='first',
            field=models.CharField(default='idk', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last',
            field=models.CharField(default='idk', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='pw',
            field=models.CharField(default='idk', max_length=180),
            preserve_default=False,
        ),
    ]
