# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-13 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20191113_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
